### ISSUE TITLE
couleurs plus douce

### ISSUE THREAD

**Issue by edouard-lopez** [boris-graeff/LaBanane#1]
Y a pas un mode soft pour la couleur de fond ? 
Quand je met `la banane` en plein écran sur mon 2e écran, ça me pique les yeux.
## Propositions
1. Une inversion du jaune et du noire pourrait marcher ;
2. Un jaune moins lumineux (e.g. `hsl(48, 100%, 70%)` = [#FFE065](http://www.colorpicker.com/FFE065)) ;
3. une [autres couleurs de banane](https://www.google.fr/search?tbs=imgo%3A1&tbm=isch&sa=1&btnG=Search&q=banane+color#tbs=imgo:1&tbm=isch&q=colors++of+banana+).

**Comment by boris-graeff** [comment]
Hum, une banane c'est jaune un point c'est tout ! ;)
Il ne me semble pas si violent ce jaune pourtant, c'est pas un problème de réglage de ton 2ème écran ?

Après en mode lecture tu peux basculer sur le mode "vidéo" où le fond est sombre.
Je note quand même l'idée de pouvoir inverser les couleurs.

**Comment by edouard-lopez** [comment]
Non non, y'a aussi des bananes [vertes, rouges-orangées et violettes](http://www.bohol.ph/pics/large/SL382709.jpg). 
J'ai des jaunes de couleurs différentes sur les 2 écrans, celui de gauche est plus verdâtre et sombre, celui de droite plus jaune flashy. Faut faire des tests utilisateurs !

## Captures & photos

### Double écrans

![labanane-dual-screen-colors](https://cloud.githubusercontent.com/assets/1212392/10784565/2dfffaaa-7d5f-11e5-9dac-464c73b2bd5d.jpg)

### Firefox mobile

paysage
![labanane-firefox-mobile-landscape](https://cloud.githubusercontent.com/assets/1212392/10784582/4a9f9dbe-7d5f-11e5-824f-2fa53cb1aa5a.png)

portrait
![labanane-firefox-mobile-portrait](https://cloud.githubusercontent.com/assets/1212392/10784574/3c28d9c6-7d5f-11e5-9adf-d1cd9e634644.png)

**Comment by boris-graeff** [comment]
Justement, le problème vient bien de ton écran. :p

**Comment by edouard-lopez** [comment]
La dernière version est beaucoup plus agréable :heart: 

![screen shot 2017-05-02 at 12 13 27](https://cloud.githubusercontent.com/assets/1212392/25614081/cc0adf06-2f30-11e7-843d-abd65ce5c6d1.png)
